### ISSUE TITLE
use pythonic naming in grablunch.py

### ISSUE THREAD

**Issue by cgoldberg** [alawibaba/autoseamless#3]
all the camelCase (aka: mixedCase) identifier naming (variables, functions, etc) is very unpythonic.  Modern Python programs should use "snake_case" naming, because_underscores_make_it_more_readable. (the exception being Class names, which use StudlyCaps).

see pep8 for details:
https://www.python.org/dev/peps/pep-0008/#prescriptive-naming-conventions

**Comment by alawibaba** [comment]
Um, SURE.

**Comment by alawibaba** [comment]
Done.
