### ISSUE TITLE
Missing automated tests

### ISSUE THREAD

**Issue by singingwolfboy** [alawibaba/autoseamless#4]
This code doesn't have an automated test suite. It's also structured in such a way that it would be very difficult to write tests for it.

**Comment by singingwolfboy** [comment]
Yay, you added a test! Now, you should make sure that it gets run automatically with a continuous integration service like [Travis CI](https://travis-ci.org/).

**Comment by cgoldberg** [comment]
https://github.com/alawibaba/autoseamless/pull/7

**Comment by cgoldberg** [comment]
landed and now running in Travis CI:
https://travis-ci.org/alawibaba/autoseamless

**Comment by alawibaba** [comment]
The only thing we don't have tests for now is the grablunch shell (which would essentially be testing argparser) and the flask frontend, which is about to undergo major changes. I think we're good for now!
