### ISSUE TITLE
Missing docstring

### ISSUE THREAD

**Issue by BenjiLee** [alawibaba/autoseamless#6]
How am I supposed to know what these functions do without a docstring? Not non-programmer friendly. I now don't have food for the week. 1/5 stars.

**Comment by cgoldberg** [comment]
btw, docstring style/conventions are described in PEP 257:
https://www.python.org/dev/peps/pep-0257/

to verify your docstrings meet proper style conventions, you can run the pep257 tool:
https://pypi.python.org/pypi/pep257

... and to automagically reformat your docstrings to meet PEP 257 conventions, you can run docformatter:
https://pypi.python.org/pypi/docformatter

**Comment by alawibaba** [comment]
Docstrings added to favorites.py, seamless_browser.py, and selector.py.
